[aruco]
; 4x4_50/4x4_100/4x4_250/4x4_1000/5x5_50/5x5_100/5x5_250/5x5_1000
dictionary = 4X4_1000
map_path=/home/orangepi/ros2_ws/src/eurus_edu/edu_aruco_navigation/maps/map.csv

[settings]
aruco_debug = true
camera_topic=/edu/downward_camera
camera_config_path=/home/orangepi/ros2_ws/src/eurus_edu/camera_calib/calibration_data.json
camera_direction=0
