[aruco]
; 4x4_50/4x4_100/4x4_250/4x4_1000/5x5_50/5x5_100/5x5_250/5x5_1000/6x6_50/6x6_100/6x6_250/6x6_1000/7x7_50/7x7_100/7x7_250/7x7_1000
dictionary = 4X4_50
map_path=/home/orangepi/ros2_ws/src/eurus_edu/edu_aruco_navigation/maps/map.txt
; TL=TopLeft, TR=TopRight, BL=BotLeft, BR=BotRight
map_origin=BR

[settings]
frequency = 30
camera_topic=/edu/camera_frame
camera_config_path=/home/orangepi/ros2_ws/src/eurus_edu/camera_calib/calibration_data.json
camera_direction=180
