; [forward_camera]
; device = /dev/forward_camera
[camera]
device = /dev/camera1
fps = 30
width = 640
height = 480

; [downward_camera]
; device = /dev/downward_camera
; fps = 30
; width = 640
; height = 480

[server]
host = 0.0.0.0
port = 8001

; [downward_camera_server]
; host = 0.0.0.0
; port = 8002