from EurusEdu import EurusControl
import time

drone = EurusControl("192.168.31.120", 65432)
drone.connect()
# time.sleep(1)
# drone.arm()
# time.sleep(5)
# time.sleep(2)
drone.takeoff(1)
# time.sleep(4)
# drone.move_to_local_point(0, 0, 1, 0)
time.sleep(5)
drone.move_to_local_point(0, 0, 1, 20)
time.sleep(5)
# print(drone.point_reached())
drone.move_to_local_point(-1, 0, 1, 20)
time.sleep(5)
# print(drone.point_reached())
# drone.move_to_local_point(0, 0, 1, 180)
# time.sleep(5)
# drone.move_to_local_point(0, 0, 1, 270)
# time.sleep(5)
# drone.move_to_local_point(0, 0, 1, 0)
# time.sleep(5)
drone.land()
# time.sleep(5)
# drone.disconnect()