[web_server]
host = 0.0.0.0
port = 5000

[systemd]
# Директория для поиска файлов сервисов.
# Для системных: /etc/systemd/system/
# Для пользовательских: /home/user/.config/systemd/user/
services_path = /home/orangepi/ros2_ws/src/eurus_edu/services

[video_topics]
aruco = /edu/aruco_debug
forward_camera = /edu/forward_camera
downward_camera = /edu/downward_camera

[applications]
# Формат: название_в_панели = /полный/путь/до/скрипта.py
example_app = /home/user/example_app.py
test_script = /home/user/test.py